### ISSUE TITLE
"Propose New Item" button don't work

### ISSUE THREAD

**Issue by mrtino** [nsa-observer/nsa-observer#1]
I'm using Firefox Aurora 32 on Xubuntu 14.04. I have the button "New item" but when I click on "Propose new item", nothing happens.

**Comment by dattaz** [comment]
Work well today. It's work for you now ?

**Comment by OpenAbricot** [comment]
Yes !

Le 14 janvier 2015 22:10:17 CET, dattaz <notifications@github.com> a écrit :
>Work well today. It's work for you now ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nsa-observer/nsa-observer/issues/1#issuecomment-69992437

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mrtino** [comment]
Yes, I forgot to close this bug.
